package gid.micro;

public enum DataType {
    return_rf,
    beta,
    beta_t1,
    aim,
    aim_t1,
    log_market_cap,
    log_market_cap_t1,
    log_btm,
    log_btm_t1,
    pin,
    pin_t1,
    fsrv,
    fsrv_t1,
    turnover,
    turnover_t1,
    illiq_amihud,
    illiq_amihud_t1,
    betaSMB,
    betaSMB_t1,
    betaHML,
    betaHML_t1,
    betaMOM,
    betaMOM_t1,
    marketReturn,
    riskFreeReturn,
    excessReturn,
    smallMinusBig,
    highMinusLow,
    momentumFactor,
    return_return
}